### ISSUE TITLE
List of todos

### ISSUE THREAD

**Issue by badabam** [badabam/capstone-project#1]
## Value proposition
**As a** user,
**I want** to create a list of todos,
**so that** I don't have to remember them.

## Description
<img src=https://user-images.githubusercontent.com/157286/174606674-9de4e11d-d652-44db-8165-b12b6dff43b7.png width=320 />

## Acceptance criteria
- [x] Items are added to the end
- [x] The form is always at the bottom
- [x] Todos scroll above the form
- [x] Whitespace is trimmed
- [x] Empty todos are not added
- [x] Maxlength is 100 chars
- [x] Items wrap

## Complexity
Small

## Tasks
- [x] Create branch
- [x] Add base styles
- [x] Setup Storybook for TodoForm
- [x] Implement TodoForm component
- [x] Write specs for TodoForm
- [x] Add TodoForm to App
- [x] Add state for `todos`
- [x] Render todos in an unordered list
