### ISSUE TITLE
Check-and-uncheck

### ISSUE THREAD

**Issue by badabam** [badabam/capstone-project#2]
## Value proposition
**As a** user,
**I want to** mark todos as done,
**so that** to see what is done without having to remember it

## Description

<img src=https://user-images.githubusercontent.com/157286/174619598-9469b06a-67ea-4e4b-93d4-8de28780e296.png width=320px>

## Acceptance criteria
- [x] New todos are unchecked
- [x] Tapping on the todo text toggles the checked state
- [x] There are only two states: checked and unchecked
- [x] Checking/unchecking does not change sort order
- [x] Checked todos are striked through

## Complexity
Small

## Tasks
- [x] Create branch
- [x] Setup stories for TodoItem
- [x] Write specs for TodoItem
- [x] Implement TodoItem
- [x] Update state logic in App with TodoItem
