### ISSUE TITLE
localStorage

### ISSUE THREAD

**Issue by badabam** [badabam/capstone-project#4]
## Value proposition

**As a** user,
**I want to** have my todos saved in the browser
**so that** I don't loose my progress in between reloads

## Description
-/-

## Acceptance criteria

- [x] All todos with their `done` state are persisted
- [x] Saving takes place immediately for each change

## Complexity

Small

## Tasks

- [x] Create branch
- [x] Add hook for localStorage
- [ ] Test with empty localStorage
