### ISSUE TITLE
Add backend

### ISSUE THREAD

**Issue by ahohnsen** [badabam/capstone-project#8]
## Value proposition

**As a** user,
**I want to** have my data on a server
**so that** I have access from multiple devices

## Description

-/-

## Acceptance criteria

- [x] Todos are persisted in backend
- [x] Screen shows '... Loading ...' while loading
- [x] New todos are rendered when the backend answered with success
- [x] Todos are added and updated after server response
- [x] Screen shows an error message if an error occurred while fetching or sending data

## Complexity

Medium

## Tasks

- [x] Create branch
- [x] Fetch data on initial run
- [x] Update addTodo and toggleTodo function
- [x] Add state for loading and error
- [x] Delete localStorage hook
